module.exports = {
  Auth: require('./auth'),
  Emailer: require('./emailer'),
  Hash: require('./hash'),
  logger: require('./logger'),
  os: require('./os'),
  randomCodesGenerator: require('./random-codes-generator'),
  validators: require('./validators'),
  User: require('./users'),
  Bill: require('./bill'),
  Customer: require('./customer'),
  Payment: require('./payment'),
  Report: require('./report'),
  cashEntry: require('./cash-entry'),
  ExportExcel: require('./export-xsls'),
  Withdraw: require('./withdraw'),
  Nitro: require('./nitro'),
}